# mybatis
mybatis:
  mapper-locations: classpath:com/springboot/mybatis/mapper/*.xml
  configuration:
    cache-enabled: true


# hikari连接池
spring:
  datasource:
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://47.103.95.233:3306/employee?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: true
      minimum-idle: 5
      pool-name: myHikari
      idle-timeout: 600000
      maximum-pool-size: 10
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

# redis
  redis:
    host: 47.103.95.233
    port: 6379